export const CPL_PLAYERS = [
    { id: 1,  name: "ABHAY VAIDYA",           mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 2,  name: "ABHISHEK PATHANIA",       mvpRank: "14", runs: "46", wickets: "3",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 3,  name: "ABHYODAY RANJAN",         mvpRank: "46", runs: "7",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 4,  name: "ADARSH VERMA",            mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 5,  name: "AJENDRASINH RATHOD",      mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 6,  name: "ALOK RATRE", mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 7,  name: "AMEY SULE",               mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 8,  name: "ANAND PRATAP",            mvpRank: "8",  runs: "76", wickets: "5",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 9,  name: "ANKUR PRAJAPATI",         mvpRank: "5",  runs: "53", wickets: "5",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 10, name: "ARNAV SINGH PATHANIA",    mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 11, name: "ARPIT PATEL",             mvpRank: "30", runs: "46", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 12, name: "ASHOK",                   mvpRank: "39", runs: "31", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 13, name: "ATHARV PARASHAR",         mvpRank: "15", runs: "8",  wickets: "3",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 14, name: "AYAN RATRE",              mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 15, name: "BHARAT CHAUDHARY",        mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 16, name: "BHAVYA",                  mvpRank: "26", runs: "18", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 17, name: "CHANDRESH THAKKAR",       mvpRank: "3",  runs: "56", wickets: "6",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 18, name: "DHAVAL SAVALIYA",         mvpRank: "51", runs: "18", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 19, name: "DHRUVAM MEHTA",           mvpRank: "25", runs: "36", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 20, name: "DR. APURVA GUPTA",        mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 21, name: "HARDIK MODI",             mvpRank: "18", runs: "10", wickets: "6",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 22, name: "HARISH KARNIK",           mvpRank: "22", runs: "28", wickets: "4",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 23, name: "HARPALSINH JADEJA",       mvpRank: "34", runs: "12", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 24, name: "HAWAN CHOUHAN",           mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 25, name: "HITANSH SHAH",            mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 26, name: "JAIMIN PATEL",            mvpRank: "9",  runs: "56", wickets: "6",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 27, name: "JAINIL PATEL",            mvpRank: "53", runs: "3",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 28, name: "JAIVAL PANDYA",           mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 29, name: "JASVANTSINH GOHIL",       mvpRank: "54", runs: "2",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 30, name: "JAYRAJ LUKOSE", mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },   
     { id: 31, name: "JAYRAJSINH GOHIL",        mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 32, name: "JIGAR THAKKER",           mvpRank: "29", runs: "33", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 33, name: "JIGNESH SHAH",            mvpRank: "44", runs: "9",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 34, name: "JITENDRASINH GOHIL",      mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 35, name: "KARAN SAGLANI",           mvpRank: "41", runs: "13", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 36, name: "KETAN DAVE", mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },  
      { id: 37, name: "KIRANSINH RATHOD",        mvpRank: "6",  runs: "21", wickets: "8",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 38, name: "KUNJAN PATEL",            mvpRank: "27", runs: "53", wickets: "1",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 39, name: "MAALAVSINH GOHIL",        mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 40, name: "MADHAV",                  mvpRank: "37", runs: "5",  wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 41, name: "MALAV AGARWAL",           mvpRank: "56", runs: "5",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 42, name: "MANAN SHAH",              mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 43, name: "MANAS MEHTA",             mvpRank: "16", runs: "60", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 44, name: "MANN BHAVSAR",            mvpRank: "32", runs: "32", wickets: "1",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 45, name: "MANN PATEL",              mvpRank: "47", runs: "4",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 46, name: "MANTHAN PRAJAPATI", mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },  
      { id: 47, name: "MEDHANSH PAREKH",         mvpRank: "33", runs: "0",  wickets: "3",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 48, name: "MEHUL SOHANI",            mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 49, name: "MIHIR DALIA",             mvpRank: "36", runs: "41", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 50, name: "MITHIL PAREKH",           mvpRank: "43", runs: "12", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 51, name: "NARENDRA BHARDWAJ",       mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 52, name: "NEELMADHAVSINH JADEJA",   mvpRank: "40", runs: "10", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 53, name: "NIKUNJ PATEL",            mvpRank: "13", runs: "25", wickets: "3",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 54, name: "PRAFUL G TRIVEDI",        mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 55, name: "PRANAV A SHETH",          mvpRank: "24", runs: "7",  wickets: "5",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 56, name: "PRANAY DARJI",            mvpRank: "12", runs: "27", wickets: "4",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 57, name: "PRASHANT BHAVSAR",        mvpRank: "11", runs: "48", wickets: "6",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 58, name: "PRATIK",                  mvpRank: "28", runs: "46", wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 59, name: "RAHIL SAGLANI",           mvpRank: "4",  runs: "24", wickets: "9",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 60, name: "RAJ D SHAH",              mvpRank: "38", runs: "6",  wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 61, name: "RAKSHIT P TRIVEDI",       mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 62, name: "RAVIRAJ PARMAR",          mvpRank: "19", runs: "50", wickets: "3",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 63, name: "RISHI SAGLANI",           mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 64, name: "RUSHI DARJI",             mvpRank: "23", runs: "49", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 65, name: "RUTUJ",                   mvpRank: "31", runs: "30", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 66, name: "SHAURIN PATEL", mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 }, 
    { id: 67, name: "SHLOK BHAVSAR",           mvpRank: "20", runs: "35", wickets: "4",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 68, name: "SMIT PATEL",              mvpRank: "7",  runs: "41", wickets: "5",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 69, name: "TIRTH PATEL",             mvpRank: "50", runs: "4",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 70, name: "UMESH TIWARI",            mvpRank: "52", runs: "7",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 71, name: "VAIBHAV SINGH",           mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 72, name: "VATSAL SHAH",             mvpRank: "2",  runs: "114",wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 73, name: "Mitanshu Patel",                  mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 74, name: "VIHAAN DALIA",            mvpRank: "42", runs: "16", wickets: "1",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 75, name: "VIRAL SEVAK",             mvpRank: "17", runs: "59", wickets: "2",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 76, name: "YASH DALIA",              mvpRank: "10", runs: "36", wickets: "6",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 77, name: "YASHRAJSINH GOHIL",       mvpRank: "NA", runs: "NA", wickets: "NA", sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 78, name: "DR NISARG SAVJIANI",      mvpRank: "1",  runs: "132",wickets: "5",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 79, name: "DHYEY PATEL",             mvpRank: "55", runs: "7",  wickets: "0",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
    { id: 80, name: "ADITYA GUPTA",             mvpRank: "35", runs: "30",  wickets: "1",  sold: false, soldTo: null, soldPrice: null, basePrice: 200 },
  ]